### ISSUE TITLE
Update README and update main docs on how to run EdgeDB docker images effectively

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-docker#17]

**Comment by Hades32** [comment]
Not sure if this issue really is about this, but the commands on https://hub.docker.com/r/edgedb/edgedb and the commands on the branch https://github.com/edgedb/edgedb-docker/tree/autobuild don't match, so that the "tutorial" on docker hub doesn't work. Subcommand `authenticate` doesn't exist yet
