### ISSUE TITLE
allow Initialization scripts

### ISSUE THREAD

**Issue by shackra** [edgedb/edgedb-docker#3]
Currently, there is no way to execute any files copied to anywhere inside the docker container as it is done for images like PostgreSQL

**Comment by 1st1** [comment]
@ambv Any comments?

**Comment by ambv** [comment]
Easy to add. We can do it for Alpha 3.

**Comment by tailhook** [comment]
As we already have `--bootstrap-script` and `--bootstrap-command`. Can I leave the this to @ambv?
This probably have to have something like this: https://www.camptocamp.com/en/news-events/flexible-docker-entrypoints-scripts
