### ISSUE TITLE
Metrics feature

### ISSUE THREAD

**Issue by Maescool** [edgedb/edgedb-docker#82]
Hi
How can we enable the metrics feature?
there is the --metrics-port thing https://github.com/edgedb/edgedb/blob/master/edb/server/args.py#L967
but the docker image doesn't seem to accept it
I tried command with this arg, and i tried env vars

**Comment by elprans** [comment]
You can do it like so: `EDGEDB_SERVER_EXTRA_ARGS="--metrics-port=1235"`

**Comment by elprans** [comment]
@raddevon, please check if `EDGEDB_SERVER_EXTRA_ARGS` is properly documented.
