### ISSUE TITLE
[Request] Adaptive backend HA env

### ISSUE THREAD

**Issue by hbriese** [edgedb/edgedb-docker#83]
It would be great if the [`--enable-backend-adaptive-ha`](https://www.edgedb.com/docs/reference/backend_ha) flag was exposed as an environmental variable

**Comment by elprans** [comment]
You can pass extra server options via `EDGEDB_SERVER_EXTRA_ARGS`, e.g:

```
EDGEDB_SERVER_EXTRA_ARGS='--enable-backend-adaptive-ha'
```
