### ISSUE TITLE
Setting server password for UI

### ISSUE THREAD

**Issue by GenarLoya** [edgedb/edgedb-docker#92]
I am trying run a docker compose edgedb server, initially using this configuration is working

```bash
version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"
```

but i want run web ui, and following the environment variables documentation, i build this configuration docker-compose.yml

```bash
version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_USER: someuser
      EDGEDB_SERVER_PASSWORD: somepassword
      EDGEDB_SERVER_PORT: 5656
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_TENANT_ID: edgedb3x
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"
```

in the first try, the ui and server is deployed but without USER and PASWORD, when put this env variables, the server cannot deploy and launch this error

```bash
edgedb-1  | INFO 48 - 2024-07-16T01:08:22.606 edb.server: loading TLS certificates
edgedb-1  | INFO 48 - 2024-07-16T01:08:26.545 edb.server: started 1 compiler worker process
edgedb-1  | INFO 48 - 2024-07-16T01:08:26.613 edb.server: Serving on 127.0.0.1:33231
edgedb-1  | INFO 48 - 2024-07-16T01:08:26.613 edb.server: Serving admin on /tmp/tmp.XyTb2Sv4m3/.s.EDGEDB.admin.33231
edgedb-1  | INFO 48 _unknown 2024-07-16T01:08:27.391 edb.server: introspecting database '__edgedbsys__'
edgedb-1  | edgedb error: AuthenticationError: authentication failed
edgedb-1  | ERROR: Migrations failed. Stopping server.
```

if USER and PASWORD not is used, the ui run but, cant access using crdentials, this login have a default values?, i was find in the docs, but i cant find.

**Comment by fmoor** [comment]
The `EDGEDB_SERVER_USER` and `EDGEDB_SERVER_PASSWORD` variables only have an effect the first time any EdgeDB server starts against a postgres instance/data directory. Did you try `docker compose down` and then `docker compose up` with your second compose file?

I was able to use your second compose file and login to the UI using the user and password.

**Comment by GenarLoya** [comment]
Ok, its working, thank you @fmoor
